version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.4.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202201-02
    environment:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Install dependencies
          command: |
            wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get install apt-transport-https
            sudo apt-get update
            sudo apt-get install dotnet-sdk-6.0
            pyenv global 3.10.2
            pip install --upgrade pip
            pip install --user aws-sam-cli==1.40.1
            dotnet tool restore
            echo 'export PATH=$PATH:/home/circleci/.local/bin' >> $BASH_ENV
      - run:
          name: Build, Validate and Publish
          command: |
            dotnet cake --target=Test-All
      - persist_to_workspace:
          root: .
          paths:
            - template.yaml
            - publish
      - run:
          name: Export Test Results
          command: dotnet trx2junit ./artifacts/*.trx
          when: always
      - store_test_results:
          path: ./artifacts/

  deploy:
    docker:
     - image: cimg/python:3.10.1
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup
      - run:
          name: Create change set
          command: |
            CHANGESET_NAME=$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
            S3_PREFIX=$STACK_NAME/$CHANGESET_NAME

            aws cloudformation package --template-file template.yaml \
               --s3-bucket $CF_DEPLOYMENT_S3_BUCKET \
               --s3-prefix $S3_PREFIX \
               --output-template-file template-packaged.yaml

            aws s3 cp template-packaged.yaml s3://$CF_DEPLOYMENT_S3_BUCKET/$S3_PREFIX/

            aws cloudformation create-change-set \
              --template-url https://s3-eu-west-1.amazonaws.com/$CF_DEPLOYMENT_S3_BUCKET/$S3_PREFIX/template-packaged.yaml \
              --stack-name $STACK_NAME \
              --change-set-name $CHANGESET_NAME \
              --description "Created by CircleCI $CIRCLE_BUILD_URL"
    environment:
      STACK_NAME: AWSLambda

# workflows:
  # version: 2
  # branch-push:
    # jobs:
      # - build-and-test:
          # context: aws-cf-deployment-dev
          # filters:
            # branches:
              # ignore: master
      # - deploy:
          # name: deploy-dev
          # context: aws-cf-deployment-dev
          # requires:
            # - build-and-test

  
  # master-push:
    # jobs:
      # - build-and-test:
          # context: aws-cf-deployment-prod
          # filters:
            # branches:
              # only: master
  